---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity: 
    storage: 179G
  storageClassName: ""
  #claimRef:
    #name: data-sonarqube-postgresql-0
    #namespace: foo
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/nfs_share/
    server: 10.0.0.206
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  #namespace: foo
spec:
  storageClassName: ""    # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-pv
spec:
  capacity: 
    storage: 10Gi
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  claimRef:
     name: data-sonarqube-postgresql-0
     namespace: sonarqube
  nfs:
    path: /mnt/nfs_share/
    server: 10.0.0.206
  persistentVolumeReclaimPolicy: Retain